#!/bin/sh

#
# This is a library of subroutines mostly intended for test scripts.
#

fail()
{
    printf "$@" 2>&1
    exit 99
}

sleepf()
{
    (sleep .1 || sleep 1) > /dev/null 2>&1
}

seq_function()
{
    if [ $# -lt 1 -o $# -gt 3 ]; then
	echo "bad args" >&2
    fi
    first=$1
    incr=1
    last=0
    case $# in
	3)
	    incr=$2
	    last=$3
	    ;;
	2)
	    last=$2
	    ;;
	1)
	    ;;
    esac
    while :; do
	printf '%d\n' $first
	first=$(( first + incr ))
	if [ $first -gt $last ]; then
	    break
	fi
    done
}

if ! seq 1 > /dev/null 2>&1; then
    seq()
    {
	seq_function "$@"
    }
fi

chr()
{
    printf "\\$(printf %03o $1)"
}
