#!/bin/sh

#
# Validate that mosh produces expected output, using screen captures
# in tmux.
#

#
# In accordance with GNU Automake, this script returns these exit
# status values:
#
# 0 test success
# 1 test failure
# 77 test skipped (tmux or ssh is unavailable if needed)
# 99 hard error
#

#
# tmux is run in command mode, always with size 80x24.  tmux output is
# logged to basename.test.log.  If tmux is unavailable the test is reported
# as skipped.
#

# This scripts takes a single argument: the name of the test being
# invoked.  It uses that as a basename for additional executables used in
# testing.  All executables are expected to return a useful exitstatus.

# `basename.client` is a program used to invoke the client and
# (possibly) generate input and capture output.  If absent, the script
# simply runs mosh directly with no input and discards output.  This
# could be used with expect to carry on a dialog with an appropriate
# server script.  This functionality is untested.

# `basename.server-baseline` is a test program invoked on the server.
# It is expected to capture a screenshot from tmux with `tmux
# capture-pane -e > basename.server-baseline.capture`.  This script
# will be run both with and without mosh and the captures will be
# compared.  If they are different, the test fails.

# `basename.server-same` is a test program invoked on the server.  It
# is intended to be used after `basename.server-baseline`, but to have
# slightly different behavior that is expected to produce the same
# output from mosh as the baseline test.  This script is only run with
# mosh.  Any difference will fail the test.  It will capture into
# basename.server-same.capture.

# `basename.server-different` is a test program invoked on the server.
# It is intended to be used after `basename.server-baseline`, but to
# have slightly different behavior that is expected to produce
# different output from mosh from the baseline test.  This script is
# only run with mosh.  Results that are the same will fail the test.
# It will capture into basename.server-same.capture

log()
{
    printf "$@"
}

error()
{
    printf "$@" >&2
}

test_success()
{
    exit 0
}
test_failure()
{
    error "$@"
    exit 1
}
test_skipped()
{
    error "$@"
    exit 77
}
test_error()
{
    error "$@"
    exit 99
}


# Tmux check.
tmux_check()
{
    local version version_major version_minor
    version=$(tmux -V)
    if [ $? != 0 ]; then
	error "tmux unavailable\n"
	return 1
    fi
    version=${version##tmux }
    version_major=${version%%.*}
    version_minor=${version##*.}
    # need version 1.8 for capture-pane
    if [ $version_major -lt 1 ] ||
	   [ $version_major -eq 1 -a $version_minor -lt 8 ]; then
	error "tmux version %s too old\n" "$version"
	return 1
    fi
    return 0
}

ssh_localhost_check()
{
    ssh localhost :
    if [ $? -ne 0 ]; then
	error "ssh to localhost failed\n"
	return 1
    fi
    return 0
}

# main

# Set up environment
if [ -z "$srcdir" ]; then
    : ${srcdir:=$PWD}
else
    srcdir="$(cd $srcdir && pwd)"
    if [ $? -ne 0 ]; then
	error "can't cd to srcdir: %s\n" "$srcdir"
	exit 99
    fi
fi
env

if ! tmux_check; then
    test_skipped "tmux unavailable\n"
fi

if [ $# -ne 1 ]; then
    test_error "not enough args\n"
fi

# Get arguments (only one so far)
test_name=$1
# XXX could use AM testsubdir macro instead
test_dir=${test_name}.d
test_script_base="${srcdir}/${test_name}"
rm -rf "${test_dir}"
mkdir "${test_dir}"

# Validate that we can run a test
if [ ! -x "${test_script_base}.server-baseline" ] \
	      || [ -f "${test_script_base}.server-same" -a ! -x "${test_script_base}.server-same" ] \
	      || [ -f "${test_script_base}.server-different" -a ! -x "${test_script_base}.server-different" ] \
	      || [ -f "${test_script_base}.server-same" -a ! -x "${test_script_base}.server-same" ] \
	      || [ -f "${test_script_base}.client" -a ! -x "${test_script_base}.client" ]; then
    test_error "test script(s) missing or not executable\n"
fi


# Run test(s).
client_wrapper=env
if [ -f "${test_script_base}.client" ]; then
    client_wrapper="${test_script_base}.client"
fi

for server_test in baseline same different; do
    testfile_name="${test_script_base}.server-${server_test}"
    if [ ! -x "${testfile_name}" ]; then
	continue
    fi
    log "Running $server_test.\n"
    if [ "$server_test" = baseline ]; then
	tests="$server_test.direct $server_test"
    else
	tests=$server_test
    fi
    for run in $tests; do
	# XXX need to quote server pathname here somehow
	tested="../../scripts/mosh --client=../frontend/mosh-client --server=$PWD/../frontend/mosh-server --local --bind-server=127.0.0.1 127.0.0.1"
	if [ "$run" = "baseline.direct" ]; then
	    tested=""
	fi
	# Actually execute code under test
	if ! ${srcdir}/hold-stdin tmux -C new-session $client_wrapper $tested "${srcdir}/render-test-server-harness" "${PWD}/${test_dir}/${run}" "${testfile_name}" > "${test_dir}/${run}.tmux.log" 2>&1; then
	    test_error "tmux failure on test %s\n" "$run"
	fi
	# Check for server harness failures
	if [ ! -s "${test_dir}/${run}.capture" ] \
	      || [ ! -s "${test_dir}/${run}.exitstatus" ]; then
	    test_error "server harness failure on test %s\n" "$run"
	fi
	read server_rv < "${test_dir}/${run}.exitstatus"
	if [ "$server_rv" -ne 0 ]; then
	    test_error "server harness exited with status %s\n" "$server_rv"
	fi
    done
    # Compare captures
    if [ "$server_test" = baseline ]; then
	file1="${test_dir}/baseline.direct.capture"
	file2="${test_dir}/baseline.capture"
    else
	file1="${test_dir}/baseline.capture"
	file2="${test_dir}/${server_test}.capture"
    fi
    if diff -q "$file1" "$file2"; then
	differ=n
    else
	differ=y
    fi
    if [ "$server_test" = different ]; then
	desired=y
	badresult=same
    else
	desired=n
	badresult=different
    fi
    if [ $differ != $desired ]; then
	test_failure "Output is %s on test %s\n" "$server_test" " $badresult"
    fi
done
