#!/bin/sh

#
# Harness script for Mosh tests, server side.  Runs test script and
# then captures screen with `tmux capture-pane`.  Captures exitstatus
# of both and returns appropriate errors.
#
if [ $# -lt 2 ]; then
    printf "not enough args\n" >&2
    exit 99
fi
testname=$1
shift
rm -f $testname.capture $testname.exitstatus
trap 'rv=$?; echo $rv > $testname.exitstatus; exit $rv' EXIT
# check for tmux
if [ -z "$TMUX_PANE" ]; then
    printf "not running under tmux\n" >&2
    exit 99
fi
# run harnessed command
eval $@
testret=$?
# sleep 1 # let remote display update
# capture screen
if ! tmux capture-pane -ept $TMUX_PANE > $testname.capture; then
    printf "tmux capture-pane failed, erroring test\n" >&2
    exit 99
fi
# return useful exitstatus from harnessed command
if [ $testret -ne 0 ]; then
    exit 1
fi
exit 0
