FROM ubuntu:latest
MAINTAINER Brett Randall <javabrett@gmail.com>

RUN apt-get update

RUN apt-get install -y openssh-server openssh-client \
	&& useradd -m mosh \
	&& echo 'mosh:m0sh-st@t1c' | chpasswd

EXPOSE 22

ENTRYPOINT service ssh start \
	&& sh
